<a href="https://colab.research.google.com/github/JolaSobera/Maczek/blob/main/ST2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Biblioteka NUMPY

NumPy – otwartoźródłowa biblioteka programistyczna dla języka Python, dodająca obsługę dużych, wielowymiarowych tabel i macierzy.

Instancje typu numpy są tablicami (wielowymiarowymi) elementów tego samego typu.

In [ ]:
import numpy as np
a = np.arange(15).reshape(5, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
b = np.array([1, 23, 0.6, "iihh"]).reshape(2,2)
print(b)

[['1' '23']
 ['0.6' 'iihh']]


In [ ]:
b = np.array([1, 23, 0.5, "imi"])
print(b)

['1' '23' '0.5' 'imi']


In [ ]:
c = np.array([[1, 2, 3], [2, 4, 5]])
print(c)

[[1 2 3]
 [2 4 5]]


 In NumPy dimensions are called axes.

    ndarray.ndim
      the number of axes (dimensions) of the array.
    ndarray.shape
      the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.

    ndarray.size
      the total number of elements of the array.

In [ ]:
print(c.ndim)

2


In [ ]:
print(c.shape)

(2, 3)


In [ ]:
print(c.size)

6


The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random.

In [ ]:
zero = np.zeros(5)
zero_2 = np.zeros((2,4))
print(zero)
print(zero_2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
jeden = np.ones(12).reshape(3,4)
random = np.empty((5, 3))
print(jeden)
print(random)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4.93720112e-310 0.00000000e+000 0.00000000e+000]
 [1.15413735e-320 2.47032823e-323 6.63424671e-310]
 [4.93818388e-310 0.00000000e+000 4.94065646e-324]
 [4.94065646e-324 0.00000000e+000 0.00000000e+000]
 [5.43472210e-323 4.93818394e-310 6.32404027e-322]]


In [ ]:
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**Arithmetic operators** on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
A = np.array([[2, 3, 5], [3, 4, 6]])
B = np.ones((2, 3))
print(A)
print(B)

[[2 3 5]
 [3 4 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(A + B)

[[3. 4. 6.]
 [4. 5. 7.]]


In [ ]:
print(np.add(A, B))

[[3. 4. 6.]
 [4. 5. 7.]]


Unlike in many matrix languages, the product `operator *`  operates elementwise in NumPy arrays. The matrix product can be performed using the `@ operator` (in python >=3.5) or the `dot function` or method:

In [ ]:
print(A * B)

[[2. 3. 5.]
 [3. 4. 6.]]


In [ ]:
print(A @ B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
C = np.ones((3, 2))

In [ ]:
print(A)
print(C)

[[2 3 5]
 [3 4 6]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print(A @ C)

[[10. 10.]
 [13. 13.]]


In [ ]:
print(A.dot(C))

[[10. 10.]
 [13. 13.]]


 `sum`, `min`, `csum` operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [ ]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
B.sum()

6.0

In [ ]:
B.sum(axis = 0 )

array([2., 2., 2.])

In [ ]:
B.sum(axis = 1)

array([3., 3.])

In [ ]:
B.cumsum(axis=0)  # cumulative sum along each row

array([[1., 1., 1.],
       [2., 2., 2.]])

NumPy provides familiar mathematical functions such as sin, cos, and exp.

In [ ]:
print(A)
np.log2(A)

[[2 3 5]
 [3 4 6]]


array([[1.        , 1.5849625 , 2.32192809],
       [1.5849625 , 2.        , 2.5849625 ]])

In [ ]:
A**3

array([[  8,  27, 125],
       [ 27,  64, 216]])

Zadanie.

Wygeneruj dowolne macierze i wykonaj działania na naich.

Indexing, Slicing and Iterating

In [ ]:
print(A)

[[2 3 5]
 [3 4 6]]


In [ ]:
M = A[::]
print(M)

[[2 3 5]
 [3 4 6]]


In [ ]:
A[1:]###A[1:,:]

array([[3, 4, 6]])

In [ ]:
A[:1]

array([[2, 3, 5]])

In [ ]:
A[:, :2]##wiersze,kolumny

array([[2, 3],
       [3, 4]])

In [ ]:
A[:,1:]

array([[3, 5],
       [4, 6]])

In [ ]:
print(A)

[[2 3 5]
 [3 4 6]]


In [ ]:
A[::-1, :]##A[::-1,:]

array([[3, 4, 6],
       [2, 3, 5]])

In [ ]:
A[:,::-1]

array([[5, 3, 2],
       [6, 4, 3]])

In [ ]:
B = np.array([
    [
        [1,2,3,4],
         [3,4,5,6]
        ],
    [
        [2,3,4,5],
        [7,8,9,1]
        ],
    [
        [3,4,5,6],
         [7,8,9,0]
        ] ,
    [
        [3,4,5,6],
         [2,3,4,5]
        ]
    ])

In [ ]:
B

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[2, 3, 4, 5],
        [7, 8, 9, 1]],

       [[3, 4, 5, 6],
        [7, 8, 9, 0]],

       [[3, 4, 5, 6],
        [2, 3, 4, 5]]])

In [ ]:
B[:,:,::-1]

array([[[4, 3, 2, 1],
        [6, 5, 4, 3]],

       [[5, 4, 3, 2],
        [1, 9, 8, 7]],

       [[6, 5, 4, 3],
        [0, 9, 8, 7]],

       [[6, 5, 4, 3],
        [5, 4, 3, 2]]])

In [ ]:
B

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[2, 3, 4, 5],
        [7, 8, 9, 1]],

       [[3, 4, 5, 6],
        [7, 8, 9, 0]],

       [[3, 4, 5, 6],
        [2, 3, 4, 5]]])

In [ ]:
B[::-1,:,:]

array([[[3, 4, 5, 6],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [7, 8, 9, 0]],

       [[2, 3, 4, 5],
        [7, 8, 9, 1]],

       [[1, 2, 3, 4],
        [3, 4, 5, 6]]])

In [ ]:
B

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[2, 3, 4, 5],
        [7, 8, 9, 1]],

       [[3, 4, 5, 6],
        [7, 8, 9, 0]],

       [[3, 4, 5, 6],
        [2, 3, 4, 5]]])

In [ ]:
B[:,::-1,:]

array([[[3, 4, 5, 6],
        [1, 2, 3, 4]],

       [[7, 8, 9, 1],
        [2, 3, 4, 5]],

       [[7, 8, 9, 0],
        [3, 4, 5, 6]],

       [[2, 3, 4, 5],
        [3, 4, 5, 6]]])

In [ ]:
B[...,::-1]

array([[[4, 3, 2, 1],
        [6, 5, 4, 3]],

       [[5, 4, 3, 2],
        [1, 9, 8, 7]],

       [[6, 5, 4, 3],
        [0, 9, 8, 7]],

       [[6, 5, 4, 3],
        [5, 4, 3, 2]]])

The dots (...) represent as many colons as needed to produce a complete indexing tuple.

Iterating over multidimensional arrays is done with respect to the first axis:

In [ ]:
for row in B:
  print(row)

[[1 2 3 4]
 [3 4 5 6]]
[[2 3 4 5]
 [7 8 9 1]]
[[3 4 5 6]
 [7 8 9 0]]
[[3 4 5 6]
 [2 3 4 5]]
